-- Security/privacy repair: deny browser access to saved foods and make invite
-- redemption rate-limited + atomic. Apply before deploying code that calls the
-- redeem_invite_atomic RPC.

BEGIN;

ALTER TABLE public.saved_foods ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.saved_foods FROM anon, authenticated;
GRANT ALL ON TABLE public.saved_foods TO service_role;

CREATE TABLE IF NOT EXISTS public.invite_redemption_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email TEXT NOT NULL,
  attempted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  success BOOLEAN NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS invite_redemption_attempts_email_time_idx
  ON public.invite_redemption_attempts (user_email, attempted_at DESC);

ALTER TABLE public.invite_redemption_attempts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.invite_redemption_attempts FROM anon, authenticated;
GRANT ALL ON TABLE public.invite_redemption_attempts TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.invite_redemption_attempts_id_seq
  TO service_role;

-- Every code that appeared in the public repository is compromised. Create a
-- fresh code out-of-band after this migration; never add it back to Git.
UPDATE public.invite_codes
   SET active = false
 WHERE code IN ('FITZONE-JOIN', 'BRICES-CREW-9K2M', 'BRICESFAMILY');

CREATE OR REPLACE FUNCTION public.redeem_invite_atomic(
  p_email TEXT,
  p_name TEXT,
  p_code TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_email TEXT := lower(trim(coalesce(p_email, '')));
  v_name TEXT := nullif(left(trim(coalesce(p_name, '')), 200), '');
  v_code TEXT := upper(regexp_replace(trim(coalesce(p_code, '')), '\s+', '', 'g'));
  v_invite public.invite_codes%ROWTYPE;
  v_recent_failures INTEGER := 0;
  v_inserted INTEGER := 0;
BEGIN
  IF v_email = '' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'email_required');
  END IF;
  IF v_code = '' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'invite_required');
  END IF;

  -- Serialize attempts for one signed-in Google account so concurrent requests
  -- cannot bypass either the rate limit or the membership uniqueness check.
  PERFORM pg_advisory_xact_lock(hashtextextended(v_email, 0));

  IF EXISTS (SELECT 1 FROM public.allowed_users WHERE email = v_email) THEN
    RETURN jsonb_build_object('ok', true, 'already', true, 'email', v_email);
  END IF;

  SELECT count(*)::INTEGER
    INTO v_recent_failures
    FROM public.invite_redemption_attempts
   WHERE user_email = v_email
     AND success = false
     AND attempted_at >= now() - interval '15 minutes';

  IF v_recent_failures >= 5 THEN
    RETURN jsonb_build_object(
      'ok', false,
      'error', 'rate_limited',
      'retry_after_seconds', 900
    );
  END IF;

  SELECT *
    INTO v_invite
    FROM public.invite_codes
   WHERE code = v_code
   FOR UPDATE;

  IF NOT FOUND OR NOT v_invite.active THEN
    INSERT INTO public.invite_redemption_attempts (user_email, success)
    VALUES (v_email, false);
    RETURN jsonb_build_object('ok', false, 'error', 'bad_invite');
  END IF;

  IF v_invite.max_uses IS NOT NULL AND v_invite.use_count >= v_invite.max_uses THEN
    INSERT INTO public.invite_redemption_attempts (user_email, success)
    VALUES (v_email, false);
    RETURN jsonb_build_object('ok', false, 'error', 'invite_exhausted');
  END IF;

  INSERT INTO public.profiles (email, name)
  VALUES (v_email, v_name)
  ON CONFLICT (email) DO UPDATE
    SET name = coalesce(profiles.name, EXCLUDED.name);

  INSERT INTO public.allowed_users (email, name, role, invite_code, joined_at)
  VALUES (v_email, v_name, 'member', v_code, now())
  ON CONFLICT (email) DO NOTHING;
  GET DIAGNOSTICS v_inserted = ROW_COUNT;

  IF v_inserted = 0 THEN
    RETURN jsonb_build_object('ok', true, 'already', true, 'email', v_email);
  END IF;

  UPDATE public.invite_codes
     SET use_count = use_count + 1
   WHERE code = v_code;

  INSERT INTO public.invite_redemption_attempts (user_email, success)
  VALUES (v_email, true);

  RETURN jsonb_build_object('ok', true, 'email', v_email);
END;
$$;

REVOKE ALL ON FUNCTION public.redeem_invite_atomic(TEXT, TEXT, TEXT)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.redeem_invite_atomic(TEXT, TEXT, TEXT)
  TO service_role;

COMMIT;
