const MEASURE_ALIASES = Object.freeze({
  calorie: "kcal",
  calories: "kcal",
  energy: "kcal",
  energy_kcal: "kcal",
  protein_g: "protein",
  fat_g: "fat",
  carbohydrate: "carbs",
  carbohydrates: "carbs",
  carbohydrate_g: "carbs",
  carbohydrates_g: "carbs",
  carbs_g: "carbs",
  net_carbohydrate: "net_carbs",
  net_carbohydrates: "net_carbs",
  net_carbs_g: "net_carbs",
  fiber_g: "fiber",
  fibre: "fiber",
  fibre_g: "fiber",
  sugar: "sugars",
  sugar_g: "sugars",
  sugars_g: "sugars",
  potassium_mg: "potassium",
  magnesium_mg: "magnesium",
  sodium_mg: "sodium",
  calcium_mg: "calcium",
  iron_mg: "iron",
  zinc_mg: "zinc",
  vitamin_a_iu: "vitamin_a",
  vitamin_c_mg: "vitamin_c",
  vitamin_d_iu: "vitamin_d",
  vitamin_e_mg: "vitamin_e",
  vitamin_k_mcg: "vitamin_k",
  vitamin_b12: "b12",
  vitamin_b12_mcg: "b12",
  b12_mcg: "b12",
  folate_mcg: "folate",
  omega_3: "omega3",
  omega_3_g: "omega3",
  omega3_g: "omega3",
  weight: "weight_lb",
  body_weight: "weight_lb",
  weight_lbs: "weight_lb",
  weight_pounds: "weight_lb",
  body_fat: "body_fat_pct",
  body_fat_percentage: "body_fat_pct",
  waist_inches: "waist_in",
  blood_glucose: "glucose_mg_dl",
  glucose: "glucose_mg_dl",
  resting_hr: "resting_heart_rate",
  resting_heart_rate_bpm: "resting_heart_rate",
  duration_minutes: "duration_min",
  distance_miles: "distance_mi",
  step_count: "steps",
  steps_count: "steps",
});

const DEFAULT_UNITS = Object.freeze({
  kcal: "kcal",
  protein: "g",
  fat: "g",
  carbs: "g",
  net_carbs: "g",
  fiber: "g",
  sugars: "g",
  potassium: "mg",
  magnesium: "mg",
  sodium: "mg",
  calcium: "mg",
  iron: "mg",
  zinc: "mg",
  vitamin_a: "IU",
  vitamin_c: "mg",
  vitamin_d: "IU",
  vitamin_e: "mg",
  vitamin_k: "µg",
  b12: "µg",
  folate: "µg",
  omega3: "g",
  weight_lb: "lb",
  body_fat_pct: "%",
  waist_in: "in",
  glucose_mg_dl: "mg/dL",
  resting_heart_rate: "bpm",
  steps: "steps",
  duration_min: "min",
  distance_mi: "mi",
  reps: "reps",
  sets: "sets",
  load_lb: "lb",
});

/** Canonical ledger id. Known unit-suffixed aliases collapse; custom ids remain valid. */
export function canonicalMeasureId(value) {
  const id = String(value || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 64);
  return MEASURE_ALIASES[id] || id;
}

export function defaultUnitForMeasure(value) {
  return DEFAULT_UNITS[canonicalMeasureId(value)] || "";
}
